{{- if .Values.persistence.longhornUIEnabled }}

{{- if .Values.ingress.traefikEnabled }}

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`{{ .Values.persistence.longhornUISubdomain }}.{{ .Values.ingress.baseDomain }}`)
      kind: Rule
      middlewares:
        - name: svc-longhorn-headers
      services:
        - name: longhorn-frontend
          port: 80
  tls:
    enabled: {{ .Values.ingress.tlsEnabled }}
    certResolver: {{ .Values.ingress.tlsCertResolver }}

{{- end }}

{{- end }}
