apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
spec:
  selector:
    app: {{ .Release.Name }}-backend-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
