apiVersion: v1
kind: Service
metadata:
  name: backend # !!! Hard coded in application as internal address !!! @TODO: Should be '{{ .Release.Name }}-backend-service'
spec:
  selector:
    app: {{ .Release.Name }}-backend-pod
  ports:
    - port: 8080
      targetPort: http-container
