apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-file-service
spec:
  replicas: {{ .Values.fileService.replicas }}
  {{- if .Values.fileService.strategy }}
  strategy:
    {{- .Values.fileService.strategy | toYaml | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-file-service-pod
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/app/file-service/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ .Chart.Name }}-file-service-pod
    spec:
      containers:
        - name: {{ .Chart.Name }}-file-service-container
          image: iqbberlin/testcenter-file-service:{{ .Values.version }}
          env:
            - name: CACHE_SERVICE_INCLUDE_FILES
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-backend-config
                  key: CACHE_SERVICE_INCLUDE_FILES
            - name: CACHE_SERVICE_ADDRESS_FOR_LUA
              valueFrom:
                configMapKeyRef:
                  name: nginx-fs-config-configmap
                  key: CACHE_SERVICE_ADDRESS_FOR_LUA
          volumeMounts:
            - name: backend-data
              mountPath: /var/www/html/
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf-in-volume
      volumes:
        - name: backend-data
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-backend-vo-data
        - name: nginx-config-volume
          configMap:
            name: nginx-fs-config-configmap
            items:
              - key: config.nginx.conf
                path: nginx.conf-in-volume
