apiVersion: v1
kind: Service
metadata:
  name: testcenter-file-service #hard coded in application as internal address
spec:
  selector:
    app: {{ .Chart.Name }}-file-service-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
