apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  {{- if .Values.frontend.strategy }}
  strategy:
    {{- .Values.frontend.strategy | toYaml | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-frontend-pod
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-frontend-pod
    spec:
      containers:
        - name: {{ .Chart.Name }}-frontend-container
          image: iqbberlin/testcenter-frontend:{{ .Values.version }}
          ports:
            - name: http-container
              containerPort: 80
