apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-frontend
spec:
  replicas: {{ .Values.deployment.frontend.replicas }}
  {{- if .Values.deployment.frontend.strategy }}
  strategy:
    {{- .Values.deployment.frontend.strategy | toYaml | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-frontend-pod
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-frontend-pod
    spec:
      containers:
        - name: {{ .Chart.Name }}-frontend-container
          image: "{{ .Values.image.frontend.registryPath }}iqbberlin/testcenter-frontend:{{ .Values.image.frontend.tag | default .Chart.AppVersion }}"
          ports:
            - name: http-container
              containerPort: 80
