apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-frontend-service
spec:
  selector:
    app: {{ .Chart.Name }}-frontend-pod
  ports:
    - name: http-service
      port: 80
      targetPort: http-container