apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db-pvc
spec:
  accessModes:
    - {{ .Values.persistence.db.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.db.size }}
  storageClassName: {{ .Values.persistence.db.storageClassName }}
