dist: bionic

services:
  - docker

install:
  - make init-dev-config
  - make run-detached

script:
  - sleep 200
  - make test-unit
  - make test-e2e

after_script:
  - make stop

after_success:
  - if [ "$TRAVIS_TAG" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
      docker build --target prod -t iqbberlin/testcenter-frontend:$TRAVIS_TAG -f docker/Dockerfile .;
      docker push iqbberlin/testcenter-frontend:$TRAVIS_TAG;
    fi
