dist: bionic

services:
  - docker

script:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
      make build-image;
      make push-image;
    fi
