dist: bionic

services:
  - docker

install:
  - make init-dev-config
  - make run-detached

script:
  - sleep 200
  - make test-unit
  - make test-e2e

after_script:
  - make stop

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
      make build-image;
      make push-image;
    fi
