# Base compose file defining services and their settings
# For concrete images check the environment specific override files.
version: '3.7'

x-env-php: &env-php
  PHP_VERSION: 7.4.22

x-env-node: &env-node
  NODE_VERSION: 14.15.0

x-env-mysql: &env-mysql
  MYSQL_DATABASE: ${MYSQL_DATABASE}
  MYSQL_USER: ${MYSQL_USER}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}

x-env-initdata: &env-initdata
  SUPERUSER_NAME: ${SUPERUSER_NAME}
  SUPERUSER_PASSWORD: ${SUPERUSER_PASSWORD}
  WORKSPACE_NAME: ${WORKSPACE_NAME}
  TEST_LOGIN_NAME: ${TEST_LOGIN_NAME}
  TEST_LOGIN_PASSWORD: ${TEST_LOGIN_PASSWORD}

x-env-logging-conf: &env-logging-conf
  max-size: "200m"
  max-file: "10"

services:

  traefik:
    container_name: testcenter-traefik
    image: traefik:v2.2
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      testcenter:

  testcenter-db:
    container_name: testcenter-db
    image: mysql:5.7
    environment:
      <<: *env-mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_INITDB_SKIP_TZINFO: 'true'
    volumes:
      - dbdata:/var/lib/mysql
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      testcenter:

  testcenter-backend:
    container_name: testcenter-backend
    environment:
      <<: *env-mysql
      <<: *env-initdata
      MYSQL_HOST: testcenter-db
      MYSQL_PORT: 3306
      BROADCAST_SERVICE_URI_PUSH: ${BROADCAST_SERVICE_URI_PUSH}
      BROADCAST_SERVICE_URI_SUBSCRIBE: ${BROADCAST_SERVICE_URI_SUBSCRIBE}
    depends_on:
      - testcenter-db
    logging:
      options:
        <<: *env-logging-conf
    volumes:
      - testcenter_backend_data:/var/www/html/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testcenter-backend.rule=(HostRegexp(`{[a-z]*}.${HOSTNAME}`) || Host(`${HOSTNAME}`)) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.testcenter-backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.testcenter-backend.middlewares=testcenter-backend-stripprefix"
    image: iqbberlin/testcenter-backend:current
    build:
      args:
        <<: *env-php
    networks:
      testcenter:

  testcenter-frontend:
    container_name: testcenter-frontend
    logging:
      options:
        <<: *env-logging-conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testcenter-frontend.rule=HostRegexp(`{[a-z]*}.${HOSTNAME}`) || Host(`${HOSTNAME}`)"
    image: iqbberlin/testcenter-frontend:current
    build:
      args:
        <<: *env-node
    networks:
      testcenter:

  testcenter-broadcasting-service:
    container_name: testcenter-broadcasting-service
    logging:
      options:
        <<: *env-logging-conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testcenter-broadcasting-service.rule=(HostRegexp(`{[a-z]*}.${HOSTNAME}`) || Host(`${HOSTNAME}`)) && PathPrefix(`/bs/public`)"
      - "traefik.http.middlewares.testcenter-broadcasting-service-stripprefix.stripprefix.prefixes=/bs"
      - "traefik.http.routers.testcenter-broadcasting-service.middlewares=testcenter-broadcasting-service-stripprefix"
    image: iqbberlin/testcenter-broadcasting-service:current
    build:
      args:
        <<: *env-node
    networks:
      testcenter:

volumes:
  dbdata:
  testcenter_backend_data:

networks:
  testcenter:
    name: testcenter