#  Compose file for production environment. Images are NOT locally built but
#  downloaded from Docker-Hub. This is the non-TLS variant using unencrypted
#  communication.
version: '3.7'

services:

  testcenter-backend:
    image: iqbberlin/testcenter-backend:11.5.5

  testcenter-frontend:
    image: iqbberlin/testcenter-frontend:8.1.1

  testcenter-broadcasting-service:
    image: iqbberlin/testcenter-broadcasting-service:4.0.0
