# Compose file for local development and testing. Images are built from
# local directories which need to be cloned from the repository.
version: '3.7'

services:

  traefik:
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

  testcenter-backend:
    build:
      context: testcenter-backend
      dockerfile: docker/Dockerfile
    volumes:
      - ./testcenter-backend:/var/www/html/
      - ./testcenter-backend/vo_data:/var/www/html/vo_data
      - testcenter_backend_vendor:/var/www/html/vendor

  testcenter-frontend:
    build:
      context: testcenter-frontend
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - ./testcenter-frontend:/app
      - testcenter_frontend_node_modules:/app/node_modules

  testcenter-broadcasting-service:
    build:
      context: testcenter-broadcasting-service
      dockerfile: docker/Dockerfile
    container_name: testcenter-broadcasting-service

volumes:
  testcenter_frontend_node_modules:
  testcenter_backend_vendor:
