version: '3.7'

x-env-mysql: &env-mysql
  MYSQL_DATABASE: ${MYSQL_DATABASE}
  MYSQL_USER: ${MYSQL_USER}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}

x-env-initdata: &env-initdata
  SUPERUSER_NAME: ${SUPERUSER_NAME}
  SUPERUSER_PASSWORD: ${SUPERUSER_PASSWORD}
  WORKSPACE_NAME: ${WORKSPACE_NAME}
  TEST_LOGIN_NAME: ${TEST_LOGIN_NAME}
  TEST_LOGIN_PASSWORD: ${TEST_LOGIN_PASSWORD}

services:

  traefik:
    image: traefik:v2.2
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.directory=/"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./config/certs/:/certs/
      - ./config/cert_config.yml:/cert_config.yml

  testcenter-db:
    image: mysql:5.7
    container_name: testcenter-db
    environment:
      <<: *env-mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_INITDB_SKIP_TZINFO: 'true'
    volumes:
      - dbdata:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf

  testcenter-backend:
    image: iqbberlin/testcenter-backend:latest
    container_name: testcenter-backend
    environment:
      <<: *env-mysql
      <<: *env-initdata
      MYSQL_HOST: testcenter-db
      MYSQL_PORT: 3306
      BROADCAST_SERVICE_URI_PUSH: ${BROADCAST_SERVICE_URI_PUSH}
      BROADCAST_SERVICE_URI_SUBSCRIBE: ${BROADCAST_SERVICE_URI_SUBSCRIBE}
    depends_on:
      - testcenter-db
    volumes:
      - testcenter_backend_vo_data:/var/www/html/vo_data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testcenter-backend.rule=Host(`${HOSTNAME}`) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.testcenter-backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.testcenter-backend.middlewares=testcenter-backend-stripprefix"
      - "traefik.http.routers.testcenter-backend.tls=true"

  testcenter-frontend:
    image: iqbberlin/testcenter-frontend:latest
    container_name: testcenter-frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testcenter-frontend.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.testcenter-frontend.tls=true"

  testcenter-broadcasting-service:
    image: iqbberlin/testcenter-broadcasting-service:latest
    container_name: testcenter-broadcasting-service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testcenter-broadcasting-service.rule=Host(`${HOSTNAME}`) && PathPrefix(`/bs`)"
      - "traefik.http.middlewares.testcenter-broadcasting-service-stripprefix.stripprefix.prefixes=/bs"
      - "traefik.http.routers.testcenter-broadcasting-service.middlewares=testcenter-broadcasting-service-stripprefix"

volumes:
  dbdata:
  testcenter_backend_vo_data:
