# Compose file for local development and testing. Images are built from
# local directories which need to be cloned from the repository.
version: '3.7'



services:
  testcenter-system-test-frontend:
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: "npx ng run testcenter-frontend:system-test"
    environment:
      - DISPLAY
      - CYPRESS_TC_TESTMODE=gui # cypress has to know this before setupNodeEvents
    user: ${CURRENT_UID}

