version: '3.7'

x-env-mysql: &env-mysql
  MYSQL_DATABASE: ${MYSQL_DATABASE}
  MYSQL_USER: ${MYSQL_USER}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}

x-env-initdata: &env-initdata
  SUPERUSER_NAME: ${SUPERUSER_NAME}
  SUPERUSER_PASSWORD: ${SUPERUSER_PASSWORD}
  WORKSPACE_NAME: ${WORKSPACE_NAME}
  TEST_LOGIN_NAME: ${TEST_LOGIN_NAME}
  TEST_LOGIN_PASSWORD: ${TEST_LOGIN_PASSWORD}

services:

  traefik:
    image: traefik:v2.2
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80" # TODO add default-port variable to make it easier to let whole setup on different port than 80 ...
      # ... this affects BROADCAST_SERVICE_URI_SUBSCRIBE in env files as well!
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  testcenter-db:
    image: mysql:5.7
    container_name: testcenter-db
    environment:
      <<: *env-mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_INITDB_SKIP_TZINFO: 'true'
    volumes:
      - dbdata:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf

  testcenter-backend:
    build:
      context: testcenter-backend
      dockerfile: docker/Dockerfile
    container_name: testcenter-backend
    environment:
      <<: *env-mysql
      <<: *env-initdata
      MYSQL_HOST: testcenter-db
      MYSQL_PORT: 3306
      BROADCAST_SERVICE_URI_PUSH: ${BROADCAST_SERVICE_URI_PUSH}
      BROADCAST_SERVICE_URI_SUBSCRIBE: ${BROADCAST_SERVICE_URI_SUBSCRIBE}
    depends_on:
      - testcenter-db
    volumes:
      - ./testcenter-backend:/var/www/html/
      - ./testcenter-backend/vo_data:/var/www/html/vo_data
      - testcenter_backend_vendor:/var/www/html/vendor
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testcenter-backend.rule=Host(`${HOSTNAME}`) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.testcenter-backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.testcenter-backend.middlewares=testcenter-backend-stripprefix"

  testcenter-frontend:
    build:
      context: testcenter-frontend
      dockerfile: docker/Dockerfile
      target: dev
    container_name: testcenter-frontend
    volumes:
      - ./testcenter-frontend:/app
      - testcenter_frontend_node_modules:/app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testcenter-frontend.rule=Host(`${HOSTNAME}`)"

  testcenter-broadcasting-service:
    build:
      context: testcenter-broadcasting-service
      dockerfile: docker/Dockerfile
    container_name: testcenter-broadcasting-service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testcenter-broadcasting-service.rule=Host(`${HOSTNAME}`) && PathPrefix(`/bs`)"
      - "traefik.http.middlewares.testcenter-broadcasting-service-stripprefix.stripprefix.prefixes=/bs"
      - "traefik.http.routers.testcenter-broadcasting-service.middlewares=testcenter-broadcasting-service-stripprefix"

volumes:
  dbdata:
  testcenter_frontend_node_modules:
  testcenter_backend_vendor:
