# Compose file for local development and testing. Images are built from
# local directories which need to be cloned from the repository.
version: '3.7'

services:
  traefik:
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    networks:
      - testcenter

  testcenter-db:
    ports:
      - "9091:3306"
    command:
      - --log_error_verbosity=2
    networks:
      - testcenter

  testcenter-backend:
    build:
      context: .
      dockerfile: backend/docker/Dockerfile
      target: dev
    volumes:
      - ./backend/.htaccess:/var/www/backend/.htaccess
      - ./backend/autoload.php:/var/www/backend/autoload.php
      - ./backend/index.php:/var/www/backend/index.php
      - ./backend/initialize.php:/var/www/backend/initialize.php
      - ./backend/routes.php:/var/www/backend/routes.php
      - ./backend/src:/var/www/backend/src
      - ./backend/test:/var/www/backend/test
      - ./data:/var/www/data
      - ./database:/var/www/database
      - ./definitions:/var/www/definitions
      - ./docs/dist:/docs/dist
      - ./package.json:/var/www/package.json
      - ./sampledata:/var/www/sampledata
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - testcenter

  testcenter-frontend:
    build:
      context: .
      dockerfile: frontend/docker/Dockerfile
      target: dev
    volumes:
      - ./common:/common
      - ./definitions:/definitions
      - ./frontend/src:/app/src
#      - ./docs/dist:/docs/dist TODO don't we need this for karma test coverage?
    networks:
      - testcenter

  testcenter-broadcasting-service:
    build:
      context: .
      dockerfile: broadcasting-service/docker/Dockerfile
      target: dev
    volumes:
      - ./common:/common
      - ./broadcasting-service/src:/app/src
    networks:
      - testcenter

  testcenter-task-runner:
    profiles:
      - task-runner
    build:
      context: .
      dockerfile: runner.Dockerfile
      args:
        HOST_UID: ${UID}
    container_name: testcenter-runner
    environment:
      TC_API_URL: http://testcenter-backend
    volumes:
      - ./CHANGELOG.md:/app/CHANGELOG.md
      - ./README.md:/app/README.md
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./node_modules:/app/node_modules
      - ./docker-compose.yml:/app/docker-compose.yml
      - ./broadcasting-service:/app/broadcasting-service
      - ./definitions:/app/definitions
      - ./dist-src:/app/dist-src
      - ./dist:/app/dist
      - ./docs:/app/docs
      - ./frontend:/app/frontend
      - ./sampledata:/app/sampledata
      - ./scripts:/app/scripts
      - ./test:/app/test
    networks:
      - testcenter
