version: '3.7'

services:

  traefik:
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:4433"
      # - "--providers.file.directory=/"

      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myhttpchallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myhttpchallenge.acme.email=postmaster@mydomain.com"
      - "--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "4433:443"
    volumes:
      - "./letsencrypt:/letsencrypt"

  testcenter-backend:
    image: iqbberlin/testcenter-backend:7.4.8
    volumes:
      - testcenter_backend_vo_data:/var/www/html/vo_data
    labels:
      - "traefik.http.routers.testcenter-backend.tls=true"

  testcenter-frontend:
    image: iqbberlin/testcenter-frontend:6.3.1
    labels:
      - "traefik.http.routers.testcenter-frontend.tls=true"

  testcenter-broadcasting-service:
    image: iqbberlin/testcenter-broadcasting-service:2.0.2
    labels:
      - "traefik.http.routers.testcenter-broadcasting-service.tls=true"

volumes:
  testcenter_backend_vo_data:
