version: '3.7'

x-env-mysql: &env-mysql
  MYSQL_DATABASE: testcenter_db
  MYSQL_USER: testcenter_user
  MYSQL_PASSWORD: testcenter_pw

services:

  testcenter-initialization-test-db:
    image: mysql:5.7
    container_name: testcenter-initialization-test-db
    environment:
      <<: *env-mysql
      MYSQL_ROOT_PASSWORD: testcenter_root_pw
      MYSQL_INITDB_SKIP_TZINFO: 'true'
    user: root
    volumes:
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    command:
      - --log_error_verbosity=1
    ports:
      - "9091:3306"
      - "22:22"
    networks:
      testcenter-initialization-test:

  testcenter-initialization-test-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: dev
    entrypoint: ["bash", "-c", "(cd /var/www && bash backend/test/initialization/tests/${TEST_NAME:-fallback}.sh)"]
    container_name: testcenter-initialization-test-backend
    environment:
      <<: *env-mysql
      MYSQL_HOST: testcenter-initialization-test-db
      MYSQL_PORT: 3306
      TESTMODE_REAL_DATA: ${TESTMODE_REAL_DATA-false}
    volumes:
      - ./backend/.htaccess:/var/www/backend/.htaccess
      - ./backend/autoload.php:/var/www/backend/autoload.php
      - ./backend/index.php:/var/www/backend/index.php
      - ./backend/initialize.php:/var/www/backend/initialize.php
      - ./backend/routes.php:/var/www/backend/routes.php
      - ./backend/src:/var/www/backend/src
      - ./backend/test:/var/www/backend/test
      - ./definitions:/var/www/definitions
      - ./package.json:/var/www/package.original.json
      - ./sampledata:/var/www/sampledata
    depends_on:
      - testcenter-initialization-test-db
    networks:
      testcenter-initialization-test:

  testcenter-initialization-test-runner:
    profiles:
      - dredd_test_against_mysql
    build:
      context: .
      dockerfile: runner.Dockerfile
    entrypoint: ["npm", "run", "backend:dredd-test"]
    container_name: testcenter-initialization-test-runner
    environment:
      TC_API_URL: http://testcenter-initialization-test-backend
    volumes:
      - ./sampledata /app/sampledata
      - ./test /app/test
    depends_on:
      - testcenter-initialization-test-db
      - testcenter-initialization-test-backend
    networks:
      testcenter-initialization-test:


networks:
  testcenter-initialization-test:
    name: testcenter-initialization-test