# Compose file for local development and testing. Images are built from
# local directories which need to be cloned from the repository.
version: '3.7'

x-env-mysql: &env-mysql
  MYSQL_DATABASE: testcenter_db
  MYSQL_USER: testcenter_user
  MYSQL_PASSWORD: testcenter_pw

services:
  traefik-system-test:
    container_name: testcenter-system-test-traefik
    image: traefik:v2.2
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - testcenter-system-test

  testcenter-system-test-db:
    image: mysql:5.7
    container_name: testcenter-system-test-db
    environment:
      <<: *env-mysql
      MYSQL_ROOT_PASSWORD: testcenter_root_pw
      MYSQL_INITDB_SKIP_TZINFO: 'true'
    user: root
    volumes:
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    command:
      - --log_error_verbosity=1
    ports:
      - "9091:3306"
      - "22:22"
    networks:
      - testcenter-system-test

  testcenter-system-test-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: dev
    container_name: testcenter-system-test-backend
    environment:
      <<: *env-mysql
      MYSQL_HOST: testcenter-system-test-db
      MYSQL_PORT: 3306
      TESTMODE_REAL_DATA: ${TESTMODE_REAL_DATA-false}
      SUPERUSER_NAME: super
      SUPERUSER_PASSWORD: user123
      WORKSPACE_NAME: example_workspace
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testcenter-backend.rule=(HostRegexp(`{[a-z]*}.${HOSTNAME}`) || Host(`${HOSTNAME}`)) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.testcenter-backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.testcenter-backend.middlewares=testcenter-backend-stripprefix"
    volumes:
      - ./backend/.htaccess:/var/www/backend/.htaccess
      - ./backend/autoload.php:/var/www/backend/autoload.php
      - ./backend/index.php:/var/www/backend/index.php
      - ./backend/initialize.php:/var/www/backend/initialize.php
      - ./backend/routes.php:/var/www/backend/routes.php
      - ./backend/src:/var/www/backend/src
      - ./backend/test:/var/www/backend/test
      - ./data:/var/www/data
      - ./database:/var/www/database
      - ./definitions:/var/www/definitions
      - ./docs/dist:/docs/dist
      - ./package.json:/var/www/package.json
      - ./sampledata:/var/www/sampledata
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - testcenter-system-test

  testcenter-system-test-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: dev
    image: iqbberlin/testcenter-frontend
    container_name: testcenter-system-test-frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testcenter-frontend.rule=HostRegexp(`{[a-z]*}.${HOSTNAME}`) || Host(`${HOSTNAME}`)"
    volumes:
      - ./common:/common
      - ./definitions:/definitions
      - ./frontend/.browserslistrc:/app/.browserslistrc
      - ./frontend/angular.json:/app/angular.json
      - ./frontend/cypress:/app/cypress
      - ./frontend/package.json:/app/package.json
      - ./frontend/src:/app/src
      - ./frontend/tsconfig.json:/app/tsconfig.json
    networks:
      - testcenter-system-test
    command: "npx ng run testcenter-frontend:serve-coverage"

  testcenter-system-test-broadcasting-service:
    build:
      context: .
      dockerfile: broadcasting-service/Dockerfile
      target: dev
    container_name: testcenter-system-test-broadcasting-service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testcenter-broadcasting-service.rule=(HostRegexp(`{[a-z]*}.${HOSTNAME}`) || Host(`${HOSTNAME}`)) && PathPrefix(`/bs/public`)"
      - "traefik.http.middlewares.testcenter-broadcasting-service-stripprefix.stripprefix.prefixes=/bs"
      - "traefik.http.routers.testcenter-broadcasting-service.middlewares=testcenter-broadcasting-service-stripprefix"
    volumes:
      - ./broadcasting-service/nest-cli.docker.json:/app/nest-cli.json
      - ./broadcasting-service/package.json:/app/package.json
      - ./broadcasting-service/src:/app/src
      - ./broadcasting-service/tsconfig.build.json:/app/tsconfig.build.json
      - ./broadcasting-service/tsconfig.json:/app/tsconfig.json
      - ./common:/common
    networks:
      - testcenter-system-test

networks:
  testcenter-system-test:
    name: testcenter-system-test