# Compose file for local development and testing. Images are built from
# local directories which need to be cloned from the repository.
version: '3.7'

services:
  testcenter-db:
    command:
      - --log_error_verbosity=1

  testcenter-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: prod
    volumes:
      - ./data:/var/www/data

  testcenter-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: prod

  testcenter-broadcasting-service:
    build:
      context: .
      dockerfile: broadcasting-service/Dockerfile
      target: prod