openapi: 3.0.0

info:
  title: IQB Testcenter API - Backend
  version: "2.0.0"

paths:
  /user/{user_id}/workspaces:
    get:
      summary: get a list of workspaces
      description: get a list of all workspaces belonging to a given user

      parameters:
        - in: header
          name: AuthToken
          schema:
            $ref: '#/components/schemas/auth'
          example:
            at: 1337ymca1337666.xxx13370
        - in: path
          name: user_id
          description: user-id
          example: 1
          required: true
          schema:
            type: integer

      responses:
        "200":
          description: List of Workspaces
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/workspace_list'
              example:
                - id: '1'
                  name: "example_workspace"
                  selected: false
                  role: ''
        "401":
          description: Not authenticated
        "500":
          description: Server Error
