apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-path-ingress-http
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`www.{{ .Values.ingress.baseDomain }}`) || Host(`{{ .Values.ingress.baseDomain }}`)
      kind: Rule
      middlewares:
        - name: securityheaders
        - name: stripregexfe
        {{- if .Values.ingress.tlsEnabled  }}
        - name: https-redirect
        {{- end }}
      services:
        - name: {{ .Release.Name }}-frontend-service
          port: 80
    - kind: Rule
      match: (Host(`www.{{ .Values.ingress.baseDomain }}`) || Host(`{{ .Values.ingress.baseDomain }}`)) && PathPrefix(`/api`)
      middlewares:
        - name: stripregexbe
        - name: securityheaders
        {{- if .Values.ingress.tlsEnabled }}
        - name: https-redirect
        {{- end }}
      services:
        - name: {{ .Release.Name }}-backend-service
          port: 80
    - kind: Rule
      match: (Host(`www.{{ .Values.ingress.baseDomain }}`) || Host(`{{ .Values.ingress.baseDomain }}`)) && PathPrefix(`/fs`)
      middlewares:
        - name: stripregexfs
        - name: securityheaders
        {{- if .Values.ingress.tlsEnabled  }}
        - name: https-redirect
        {{- end }}
      services:
        - name: testcenter-file-service #hard coded in application as internal address
          port: 80
    - kind: Rule
      match: (Host(`www.{{ .Values.ingress.baseDomain }}`) || Host(`{{ .Values.ingress.baseDomain }}`)) && PathPrefix(`/bs/public`)
      middlewares:
        - name: stripregexbs
        - name: securityheaders
        {{- if .Values.ingress.tlsEnabled  }}
        - name: https-redirect
        {{- end }}
      services:
        - name: testcenter-broadcasting-service #hard coded in application as internal address
          port: 3000

{{- if .Values.ingress.tlsEnabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-path-ingress-https
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.{{ .Values.ingress.baseDomain }}`) || Host(`{{ .Values.ingress.baseDomain }}`)
      kind: Rule
      middlewares:
        - name: securityheaders
        - name: stripregexfe
      services:
        - name: {{ .Release.Name }}-frontend-service
          port: 80
    - kind: Rule
      match: (Host(`www.{{ .Values.ingress.baseDomain }}`) || Host(`{{ .Values.ingress.baseDomain }}`)) && PathPrefix(`/api`)
      middlewares:
        - name: stripregexbe
        - name: securityheaders
      services:
        - name: {{ .Release.Name }}-backend-service
          port: 80
    - kind: Rule
      match: (Host(`www.{{ .Values.ingress.baseDomain }}`) || Host(`{{ .Values.ingress.baseDomain }}`)) && PathPrefix(`/fs`)
      middlewares:
        - name: stripregexfs
        - name: securityheaders
      services:
        - name: testcenter-file-service #hard coded in application as internal address
          port: 80
    - kind: Rule
      match: (Host(`www.{{ .Values.ingress.baseDomain }}`) || Host(`{{ .Values.ingress.baseDomain }}`)) && PathPrefix(`/bs/public`)
      middlewares:
        - name: stripregexbs
        - name: securityheaders
      services:
        - name: testcenter-broadcasting-service #hard coded in application as internal address
          port: 3000
#  tls: {} #dev-deploy: use this line for self signed certs
#wip for acme
  tls:
#    options:
#      name: default
    certResolver: letsencrypt
    domains:
      - main: {{ .Values.ingress.baseDomain }}
        sans:
          - www.{{ .Values.ingress.baseDomain }}
{{- end }}
