apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripregexfe
spec:
  redirectRegex:
    regex: ^http(s?)://www\.(.*)
    replacement: http${1}://${2}

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripregexbe
spec:
  stripPrefix:
    prefixes:
      - "/api"

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripregexfs
spec:
  stripPrefix:
    prefixes:
      - "/fs"

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripregexbs
spec:
  stripPrefix:
    prefixes:
      - "/bs/public"

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: securityheaders
spec:
  headers:
    contentTypeNosniff: true
    customFrameOptionsValue: "SAMEORIGIN"
    referrerPolicy: "no-referrer"
    stsIncludeSubdomains: true
    stsSeconds: 31536000

---
# First, define a RedirectScheme middleware
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
spec:
  redirectScheme:
    scheme: https
    port: "{{ .Values.ingress.tlsPort }}"
    permanent: true
