apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-backend-config
  annotations:
    {{- include "config.annotations" . | nindent 4 }}
data:
  VERSION: {{ .Values.version | quote }}
  HOSTNAME: {{ .Values.config.hostname | quote }}
  PORT_OF_REVERSE_PROXY: {{ .Values.config.port | quote }}
  TLS_PORT_OF_REVERSE_PROXY: {{ .Values.config.tlsPort | quote }}
  TLS_ENABLED: {{ .Values.config.tlsEnabled | quote }}
  MYSQL_DATABASE: {{ .Values.config.mysqlDatabase | quote }}
  MYSQL_USER: {{ .Values.config.mysqlUser | quote }}
  BROADCAST_SERVICE_ENABLED: {{ .Values.config.broadcastServiceEnabled | quote }}
  FILE_SERVICE_ENABLED: {{ .Values.config.fileServiceEnabled | quote }}
  CACHE_SERVICE_RAM: {{ .Values.config.cacheServiceRam | quote }}
  CACHE_SERVICE_INCLUDE_FILES: {{ .Values.config.cacheServiceIncludeFiles | quote }}
  DOCKER_DAEMON_MTU: {{ .Values.config.dockerDaemonMtu | quote }}
  DOCKERHUB_PROXY: {{ .Values.config.dockerhubProxy | quote }}
  RESTART_POLICY: {{ .Values.config.restartPolicy | quote }}
  OVERWRITE_INSTALLATION: {{ .Values.config.overwriteInstallation | quote }}
  SKIP_READ_FILES: {{ .Values.config.skipReadFiles | quote }}
  SKIP_DB_INTEGRITY: {{ .Values.config.skipDbIntegrity | quote }}
  NO_SAMPLE_DATA: {{ .Values.config.noSampleData | quote }}
