apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-backend-pvc
spec:
  accessModes:
    - {{ .Values.persistence.backend.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.backend.size }}
  storageClassName: {{ .Values.persistence.backend.storageClassName }}
