openapi: 3.0.0

info:
  title: IQB Testcenter API - Backend
  version: "2.0.0"

paths:

  /booklet/{booklet_name}/state:
    get:
      summary: get status of a booklet
      description: retrieves some status informations of a booklet
      parameters:
        - in: header
          name: AuthToken
          description: auth-token for test-user containing a loginToken

          schema:
            $ref: './components.spec.yml#/components/schemas/auth_test'
          example:
            l: user000000000.test0000000
        - in: path
          name: booklet_name
          description: id of a executed test
          example: "BOOKLET.SAMPLE"
          required: true
          schema:
            type: string
        - in: query
          name: code
          description: person code TODO replace this and work with personCode instead.
          schema:
            type: string
          example: xxx
      responses:
        "200":
          description: a object containg information about booklet
          content:
            application/json:
              example:
                running: true
                id: 0
                lastState: ""
                locked: false
                label: "BLA"
        "401":
          description: Not authenticated
        "410":
          description: Session Expired
        "403":
          description: Forbidden
        "500":
          description: Server Error
