openapi: 3.0.0

info:
  title: IQB Testcenter API - Backend
  description: This a spec for the (REST-) API of the IQB-Tetscenter APP. It will be used to make backend's e2e-test and a mock-server for frontend's e2e-tests. It's the basis for out vision of continuous integration.
  version: "2.0.0"

paths:

components:
  schemas:

    auth:
      type: object
      properties:
        at:
          type: string
          description: authtoken für admin and maybe super admin modules
          example: user000000000.superadmin0
      required:
        - at

    auth_test:
      type: object
      properties:
        p:
          type: string
          description: authtoken für test module - person
          example: person00000000.test0000000
        l:
          type: string
          description: authtoken für test module - login
          example: person00000000.test0000000
      required:
        - l


    login_request:
      type: object
      properties:
        name:
          type: string
          description: Username
          example: super
        password:
          type: string
          description: Password
          example: user123

    admin_session:
      type: object
      properties:
        adminToken:
          type: string
          description: "Token for session authentication"
        name:
          type: string
          description: Username repetition
          example: super
        workspaces:
          type: array
          description: "List of workspaces wich are open to this user"
          items:
            $ref: '#/components/schemas/workspace'
        isSuperadmin:
          type: boolean
          description: "Flag that tells, if this user is a superadmin"
          example: true

    login_session:
      type: object
      required:
        - workspaceId
        - groupName
        - name
        - mode
        - booklets
      properties:
        workspaceId:
          type: number
          description: this session belongs to workspace with this Id
          example: 1
        groupName:
          type: string
          description: name of loginGroup to this belongs to
          example: "sample_group"
        name:
          type: string
          description: name of the login
          example: "sample_login"
        mode:
          type: string
          description: |-
            mode of the current login-group
            currently known modes are
             * run-hot-return - hot run of testLet, can save answers etc.,
                session gets stored and can be revoked
             * run-hot-restart - hot run of testLet, can save answers etc.,
                every session starts all tests again and have unique Tokens
             * run-review - run a review round of testLet, reviewes can be saved, but no answers
                At the moment we distinguish between hot, trial and review in the GUI and there are no real
                checks for the mode in this backend, except for the difference between `run-hot-return` and
                `run-hot-restart`.
             * run-trial - run a trial round
             * monitor-study - TBA
             * monitor-login - TBA
          example: "run-hot-return"
        booklets:
          type: object
          description: An object containing information of login codes and available booklets for this group.
          example:
            xxx:
              - BOOKLET.SAMPLE
        customTexts:
          type: object
          description: An Object containing customtext-strings for the UI as key-value-pairs
          example:
            somestr: string
        loginToken:
          type: string
          description: the token for this session (available after two-factor-authorization part I)
          example: "login00000000.test0000000"
        personToken:
          type: string
          description: the token for this person (available after two-factor-authorization part II)
          example: "person00000000.test0000000"
        code:
          type: string
          description: login-code this person (available after two-factor-authorization part II)
          example: "xxx"
        testId:
          type: number
          description: number of currently running test, 0 if none
          example: 0
        bookletLabel:
          type: string
          description: label of booklet of currently running test if any
          example: ""

    workspace:
      type: object
      properties:
        id:
          type: string
          example: "1"
        name:
          type: string
          example: "example_workspace"
        role:
          type: string
          example: "RW"
        selected:
          type: boolean
          example: false
          description: TODO what does this do?
      required:
        - id

    workspace_list:
      type: array
      description: List of Workspaces
      items:
        $ref: '#/components/schemas/workspace'

    user_list:
      type: array
      description: List of Users
      items:
        $ref: '#/components/schemas/user'

    user:
      type: object
      description: a user
      properties:
        name:
          type: string
          example: super
        id:
          type: string
          example: "1"
        email:
          type: string
          nullable: true
          example: null
        isSuperadmin:
          type: string # dredd does not support enum, otherwise it would be enum["1", "2"]
          example: "1"
        selected:
          type: boolean
          example: true
          description: TODO what does this do?
        role:
          type: string #dredd does not support enum
          example: "RW"
      required:
        - id
        - name

    file:
      type: object
      description: information about a file
      properties:
        filename:
          type: string
        filesize:
          type: integer
          description: file size in byte
        filesizestr:
          type: string
          description: human readable filesize
        filedatetime:
          type: integer
          description: modification date as unix time stamp
        filedatetimestr:
          type: string
          description: modification date as human readable string
        type:
          type: string
          description: Testtakers | Booklet | Resource | Unit | SysCheck
        typelabel:
          type: string
          description: Testtakers | Booklet | Resource | Unit | SysCheck

    file_list:
      type: array
      description: List of Files
      items:
        $ref: '#/components/schemas/file'

    sys_check:
      type: object
      description: Configuration of a SysCheck
      properties:
        name:
          description: name of the SysCheck as defiend in the XML-file
          type: string
        label:
          description: label to display
          type: string
        questions:
          description: set of questions for the questionaire
          type: array
          items:
            $ref: '#/components/schemas/question_def'
        hasUnit:
          description: is there a unit for this SysCheck?
          type: boolean
        canSave:
          description: is saving SysCheck-Report allowed?
          type: boolean
        customTexts:
          description: CustomTexts
          type: object
        skipNetwork:
          description: skip the network test?
          type: boolean
        downloadSpeed:
          $ref: '#/components/schemas/speed_params'
        uploadSpeed:
          $ref: '#/components/schemas/speed_params'
        workspaceId:
          description: on which workspace is this SysCheck?
          type: number

    speed_params:
      type: object
      description: paramaters of a speed-check
      properties:
        min:
          description: minimal speed to get a `sufficient` rating in **Bytes per second**
          type: number
          example: 1.875e+6
        good:
          description: minimal speed to get a `good` rating in **Bytes per second**
          type: number
          example: 3.75e+6
        maxDevianceBytesPerSecond:
          description: maximal deviance allowed to pass one round of regeression test in **Bytes per second**
          type: number
          example: 100000
        maxErrorsPerSequence:
          description: allow this number of errors in one sequence and still pass, normally 0
          type: integer
          example: 0
        maxSequenceRepetitions:
          description: how many test sequences should be run (if they exceedmax deviance), minimum is 3
          type: integer
          example: 15
        sequenceSizes:
          description: array of numbers describing the packagae sized for each sequence
          type: array
          items:
            type: integer
          example:
            - 400000
            - 800000
            - 1600000
            - 3200000

    question_def:
      type: object
      description: definition of a SysCheck-questionaire
      properties:
        id:
          type: number
          description: identifier of the question
          example: 1
        type:
          description: type of the questions, like 'header', 'string', 'select', 'text', 'check', 'radio'
          type: string
          example: select
        prompt:
          description: Question text
          type: string
          example: "What is the capital of Switzerland?"
        options:
          description: list of options for type `check` or `select`
          type: array
          items:
            type: string
          example:
            - Bern
            - Zurich
        required:
          description: is this question required
          type: boolean
          example: false
