openapi: 3.0.0

info:
  title: IQB Testcenter API - Backend
  version: "2.0.0"

paths:

  /session:
    get:
      summary: get a session
      description: returns session data according to a AuthToken.
        The type of the session is deteced by the type of the token. The auth-token is a JSON-array in the header
        `AuthToken`, containing the field `l` with a login-session-token (two-factor-authentication part I only),
        `p` with a person token (authenticated as testee or test-commander), or `at` with an admin (authenticated as
        administrator).
        If there are several tokens in the header, only one session can be returned. Existance of sessions to the tokens
        are proved in the order `login`, `person`, `admin`.
      parameters:
        - in: header
          name: AuthToken
          description: auth-token for test-user
          schema:
            $ref: './components.spec.yml#/components/schemas/auth_test'
          example:
#            l: user000000000.test0000000
            p: 0000000000000.00000000000
#            at: user000000000.rw00000000
      responses:
        "200":
          description: OK, get session data
          content:
            application/json:
              schema:
                $ref: './components.spec.yml#/components/schemas/session'
              example:
                token:  "static_token_person_xxx"
                displayName: "sample_group/sample_user/xxx"
                access:
                  test:  ["BOOKLET.SAMPLE"]
                customTexts: {} # due to https://github.com/iqb-berlin/testcenter-iqb-php/issues/53 get customTexts
                flags: []

        "401":
          description: No token qualifies for authentication
        "410":
          description: Session Expired
        "500":
          description: Server Error


  /session/admin:
    put:
      summary: Start Admin Session
      description: Starts a Session as Admin by Username and password

      requestBody:
        content:
          application/json:
            schema:
              $ref: './components.spec.yml#/components/schemas/login_request'

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.spec.yml#/components/schemas/session'
              example:
                token: user000000000.0000000000
                displayName: super
                access:
                  workspaceAdmin: [1]
                  superAdmin: []
        "202":
          description: User has account but neither workspace nor super-admin privilige
        "400":
          description: Insufficent Crendetials
        "500":
          description: Server Error

  /session/login:
    put:
      summary: Start Login Session
      description: Starts a Session as Login by Username and password
        This is Part I of the two-factor authentication. Get a token for a login, defined in a `Testtakers.xml`-file,
        together with some session information like running tests etc.

      requestBody:
        content:
          application/json:
            schema:
              $ref: './components.spec.yml#/components/schemas/login_request'
            example:
              name: test
              password: user123

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.spec.yml#/components/schemas/session'
              example:
                token:  "static_token_login_sample_login"
                displayName: "sample_group/sample_user"
                access: {}
                customTexts: {} # due to https://github.com/iqb-berlin/testcenter-iqb-php/issues/53 get customTexts
                flags: ['requireCode']
        "400":
          description: Insufficent Crendetials
#        "410": - must be removed because test fails other wise... TODO find better solution
#          description: Session Expired
        "500":
          description: Server Error

  /session/person:
    put:
      summary: Start Person Session
      description: Starts a Session for a Person, on the basis of LoginToken (!)
        which is Part II of the Two-Factor Authentication. Get a token for a person belonging to a login, as defined in
        a `Testtakers.xml`-file, together with some information about this person

      parameters:
        - in: header
          name: AuthToken
          description: auth-token for test-user
          schema:
            $ref: './components.spec.yml#/components/schemas/auth_test'
          example:
            l: user000000000.test0000000

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
            example:
              code: 'xxx'

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.spec.yml#/components/schemas/session'
              example:
                token:  "static_token_person_xxx"
                displayName: "sample_group/sample_user/xxx"
                access:
                  test:
                    - ["BOOKLET.SAMPLE"]
                customTexts: {} # due to https://github.com/iqb-berlin/testcenter-iqb-php/issues/53 get customTexts
                flags: []
        "400":
          description: Insufficent Crendetials
        "410":
          description: Session Expired
        "500":
          description: Server Error
