openapi: 3.0.0

info:
  title: IQB Testcenter API - Backend
  version: "2.0.0"

paths:
  /list/routes:
    get:
      summary: Lists all available endpoints

      responses:
        "200":
          description: OK
          content:
            application/json:
              example:
                - "[GET] /list/routes"
        "500":
          description: Server Error

  /system/config:
    get:
      summary: get system config
      description: returns publicy avaialable parts of system config
        - version number
        - customTexts for UI
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    example: "2.0.0"
                  customTexts:
                    type: object
                required:
                  - version
                  - customTexts
        "500":
          description: Server Error

  /specstatus:
    get:
      summary: temporary helper endpoint

      responses:
        "200":
          description: OK

  /version:
    get:
      summary: get API version
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                properties:
                  version:
                    type: string
              example:
                version: "2.0.0-beta"

  /workspaces:
    get:
      summary: get a list of workspaces
      description: get a list of all workspaces

      parameters:
        - in: header
          name: AuthToken
          description: auth-token for admin-user with super-admin privilege
          schema:
            $ref: './components.spec.yml#/components/schemas/auth'
          example:
            at: user000000000.superadmin0

      responses:
        "200":
          description: List of Workspaces
          content:
            application/json:
              schema:
                $ref: './components.spec.yml#/components/schemas/workspace_list'
              example:
                - id: '1'
                  name: "example_workspace"

        "401":
          description: Not authenticated
        "403":
          description: Forbidden
        "500":
          description: Server Error

    delete:
      summary: delete some workspaces
      description: deletes a list of workspaces given by their ids

      parameters:
        - in: header
          name: AuthToken
          description: auth-token for admin-user with super-admin privilege
          schema:
            $ref: './components.spec.yml#/components/schemas/auth'
          example:
            at: user000000000.superadmin0

      requestBody:
        content:
          application/json:
            schema:
              properties:
                ws:
                  type: array
                  description: list of Workspace-Id
                  items:
                    type: integer
              required:
                - ws
            example:
              ws: [2]

      responses:
        "401":
          description: Not authenticated
        "403":
          description: Forbidden
        "500":
          description: Server Error

  /users:
    get:
      summary: get a list of users
      description: returns info about all registered users.

      parameters:
        - in: header
          name: AuthToken
          description: auth-token for admin-user with super-admin privilege
          schema:
            $ref: './components.spec.yml#/components/schemas/auth'
          example:
            at: user000000000.superadmin0

      responses:
        "200":
          description: List of users
          content:
            application/json:
              schema:
                $ref: './components.spec.yml#/components/schemas/user_list'
              example:
                - name: super
                  id: '1'
                  email: null
                  is_superadmin: '1'
        "401":
          description: Not authenticated
        "403":
          description: Forbidden
        "500":
          description: Server Error

    delete:
      summary: delete some users
      description: deletes a list of given user-ids. ids wich did not exist get skipped; in other words there is no
        check if the user existed beforeheand.

      parameters:
        - in: header
          name: AuthToken
          description: auth-token for admin-user with super-admin privilege
          schema:
            $ref: './components.spec.yml#/components/schemas/auth'
          example:
            at: user000000000.superadmin0

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                u:
                  type: array
                  items:
                    type: string
                    description: user-id
            example:
              u:
                - 2

      responses:
        "200":
          description: ok
        "401":
          description: Not authenticated
        "403":
          description: Forbidden
        "500":
          description: Server Error
