openapi: 3.0.0

info:
  title: IQB Testcenter API - Backend
  version: "2.0.0"

paths:

  /test/{test_id}:
    get:
      summary: get a test
      description: retrieves a certain executed test - the booklet-file XML, last state and lock status
      parameters:
        - in: header
          name: AuthToken
          description: auth-token for test-user
          schema:
            $ref: './components.spec.yml#/components/schemas/auth_test'
          example:
            l: user000000000.test0000000
            p: 0000000000000.00000000000
        - in: path
          name: test_id
          description: id of a executed test
          example: 1
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: List of Workspaces
#          content: TODO - include sample file!
#            application/json:
#              example:
#                laststate: []
#                locked: false
#                xml: ""
        "401":
          description: Not authenticated
        "403":
          description: Forbidden
        "500":
          description: Server Error

  /test/{test_id}/unit/{unit_name}:
    get:
      summary: get a unit of a test
      description: retrieves a certain unit from a certain executed test - the booklet-file XML, last state and lock status
      parameters:
        - in: header
          name: AuthToken
          description: auth-token for test-user
          schema:
            $ref: './components.spec.yml#/components/schemas/auth_test'
          example:
            l: user000000000.test0000000
            p: 0000000000000.00000000000
        - in: path
          name: test_id
          description: id of a executed test
          example: 1
          required: true
          schema:
            type: integer
        - in: path
          name: unit_name
          description: unit-name (not alias!) as defined in booklet
          example: ''
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of Workspaces
#          content: TODO - include sample file!
#            application/json:
#              example:
#                laststate: []
#                locked: false
#                xml: ""
        "401":
          description: Not authenticated
        "403":
          description: Forbidden
        "500":
          description: Server Error

  /resource/{resource_name}:
    get:
      summary: get resource by name
      description: retrieves a resource-file by its name (filename without extension)
      parameters:
        - in: header
          name: AuthToken
          description: auth-token for test-user
          schema:
            $ref: './components.spec.yml#/components/schemas/auth_test'
          example:
            l: user000000000.test0000000
            p: 0000000000000.00000000000
        - in: path
          name: resource_name
          description: resource_name (filename without XML-extension)
          example: 1
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of Workspaces
        #          content: TODO - include sample file!
        #           text/plain:
        #              example:
        "401":
          description: Not authenticated
        "403":
          description: Forbidden
        "500":
          description: Server Error

  /test/{test_id}/unit/{unit_name}/review:
    put:
      summary: add review to unit
      description: add a review item to unit in a test
      parameters:
        - in: header
          name: AuthToken
          description: auth-token for test-user
          schema:
            $ref: './components.spec.yml#/components/schemas/auth_test'
          example:
            l: user000000000.test0000000
            p: 0000000000000.00000000000
        - in: path
          name: test_id
          description: test-id - id of a test execution.
          example: 1
          required: true
          schema:
            type: string
        - in: path
          name: unit_name
          description: unit-name (or alias) as defined in booklet
          example: 1
          required: true
          schema:
            type: string
      responses:
        "201":
          description: OK, created
        "401":
          description: Not authenticated
        "403":
          description: Forbidden
        "500":
          description: Server Error

  /test/{test_id}/review:
    put:
      summary: add review to booklet
      description: add a review item to a certain booklet
      parameters:
        - in: header
          name: AuthToken
          description: auth-token for test-user
          schema:
            $ref: './components.spec.yml#/components/schemas/auth_test'
          example:
            l: user000000000.test0000000
            p: 0000000000000.00000000000
        - in: path
          name: test_id
          description: test-id - id of a test execution.
          example: 1
          required: true
          schema:
            type: string
      responses:
        "201":
          description: OK, created
        "401":
          description: Not authenticated
        "403":
          description: Forbidden
        "500":
          description: Server Error
