secret:
  backend:
    mysqlUser: &dbUser iqb_tba_db_user
    mysqlPassword: &dbUserPassword change_me
    passwordSalt: change_me

  db:
    mysqlUser: *dbUser
    mysqlPassword: *dbUserPassword
    mysqlRootPassword: change_me

ingress:
  traefikEnabled: false
  baseDomain: testcenter.domain.tld
  httpPort: 80
  httpsPort: 443
  tlsEnabled: false

persistence:
  longhornEnabled: false

  cacheServerPvcStorageClassName: standard
  cacheServerPvcAccessMode: ReadWriteOnce

  backendPvcStorageClassName: standard
  backendPvcAccessMode: ReadWriteOnce

  dbPvcStorageClassName: standard
  dbPvcAccessMode: ReadWriteOnce
