apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-bs-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.broadcastingService.replicas }}
  {{- if .Values.broadcastingService.strategy }}
  strategy:
  {{- .Values.broadcastingService.strategy | toYaml | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-bs-pod
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-bs-pod
    spec:
      containers:
        - name: {{ .Chart.Name }}-bs-container
          image: iqbberlin/testcenter-broadcasting-service:{{ .Chart.Version }}
          ports:
            - name: http-container
              containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: testcenter-broadcasting-service #hard coded in application as internal address
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}-bs-pod
  ports:
    - name: http-service
      port: 3000
      targetPort: http-container