apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbdata
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.volume.dbdata.accessMode }}
  resources:
    requests:
      storage: {{ .Values.volume.dbdata.size }}
  storageClassName: {{ .Values.volume.dbdata.storageClassName }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testcenter-backend-vo-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.volume.vodata.accessMode }}
  resources:
    requests:
      storage: {{ .Values.volume.vodata.size }}
  storageClassName: {{ .Values.volume.vodata.storageClassName }}
