# Compose file for local development and testing. Images are built from
# local directories which need to be cloned from the repository.

services:
  traefik:
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    networks:
      - testcenter

  testcenter-db:
    ports:
      - "9091:3306"
    command:
      - "--explicit-defaults-for-timestamp=TRUE"
      - "--sql-mode=PIPES_AS_CONCAT,ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
      - "--tls-version=TLSv1.2,TLSv1.3"
      - "--max-connections=500"
      - "--log_error_verbosity=2"
    volumes:
      - ../scripts/database/000-create-test-db.sh:/docker-entrypoint-initdb.d/000-create-test-db.sh
    networks:
      - testcenter

  testcenter-backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
      target: dev
      args:
        BUILDKIT_INLINE_CACHE: 1
      cache_from:
        - iqbberlin/testcenter-backend:dev
      tags:
        - iqbberlin/testcenter-backend:dev
    volumes:
      - ../backend/.htaccess:/var/www/testcenter/backend/.htaccess
      - ../backend/config/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ../backend/config/local.php.ini:/usr/local/etc/php/conf.d/local.ini
      - ../backend/config/no-cors.htaccess/:/var/www/testcenter/.htaccess
      - ../backend/config/vhost.conf:/etc/apache2/sites-available/vhost.conf
      - ../backend/index.php:/var/www/testcenter/backend/index.php
      - ../backend/initialize.php:/var/www/testcenter/backend/initialize.php
      - ../backend/routes.php:/var/www/testcenter/backend/routes.php
      - ../backend/src:/var/www/testcenter/backend/src
      - ../backend/test:/var/www/testcenter/backend/test
      - ../data:/var/www/testcenter/data
      - ../definitions:/var/www/testcenter/definitions
      - ../docs/dist:/docs/dist
      - ../package.json:/var/www/testcenter/package.json
      - ../sampledata:/var/www/testcenter/sampledata
      - ../scripts/database:/var/www/testcenter/scripts/database
    environment:
      TLS_ENABLED: ${TLS_ENABLED:-off}
    ports:
      - 9005:9003
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - testcenter

  testcenter-frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
      target: dev
      args:
        BUILDKIT_INLINE_CACHE: 1
      cache_from:
        - iqbberlin/testcenter-frontend:dev
      tags:
        - iqbberlin/testcenter-frontend:dev
    volumes:
      - ../common:/usr/src/testcenter/common
      - ../definitions:/usr/src/testcenter/definitions
      - ../frontend/src:/usr/src/testcenter/frontend/src
      - ../docs/dist:/docs/dist
    networks:
      - testcenter

  testcenter-broadcasting-service:
    build:
      context: ..
      dockerfile: broadcasting-service/Dockerfile
      target: dev
      args:
        BUILDKIT_INLINE_CACHE: 1
      cache_from:
        - iqbberlin/testcenter-broadcasting-service:dev
      tags:
        - iqbberlin/testcenter-broadcasting-service:dev
    volumes:
      - ../common:/usr/src/testcenter/common
      - ../broadcasting-service/src:/usr/src/testcenter/broadcasting-service/src
      - ../docs/dist:/docs/dist
    networks:
      - testcenter

  testcenter-file-service:
    build:
      context: ..
      dockerfile: file-service/Dockerfile
      args:
        ENABLED_MODULES: lua
        BUILDKIT_INLINE_CACHE: 1
      cache_from:
        - iqbberlin/testcenter-file-service
      tags:
        - iqbberlin/testcenter-file-service
    volumes:
      - ../sampledata/sample_resource_package.itcr.zip:/var/www/data-TEST/ws_1/Resource/sample_resource_package.itcr.zip
      - ../sampledata/SAMPLE_UNITCONTENTS.HTM:/var/www/data-TEST/ws_1/Resource/SAMPLE_UNITCONTENTS.HTM
      - ../sampledata/verona-player-simple-6.0.html:/var/www/data-TEST/ws_1/Resource/verona-player-simple-6.0.html
      - ../data:/var/www/html/
      - ../file-service/nginx.conf:/etc/nginx/nginx.conf
      - ../file-service/auth/:/usr/share/nginx/auth
      - ../file-service/no-cors.conf:/etc/nginx/conf.d/cors.conf
    networks:
      - testcenter

  testcenter-cache-service:
    ports:
      - "6379:6379"

  testcenter-task-runner:
    container_name: testcenter-task-runner
    profiles:
      - task-runner
    build:
      context: ..
      dockerfile: docker/runner.Dockerfile
    volumes:
      - ../README.md:/app/README.md
      - ../broadcasting-service:/app/broadcasting-service
      - ../common:/app/common
      - ../definitions:/app/definitions
      - ../dist-src:/app/dist-src
      - ../dist:/app/dist
      - ../docker/docker-compose.yml:/app/docker-compose.yml
      - ../docs:/app/docs
      - ../frontend:/app/frontend
      - ../package.json:/app/package.json
      - ../sampledata:/app/sampledata
      - ../scripts:/app/scripts
      - ../test/api:/app/test/api
      - ../test/config.docker.json:/app/test/config.json
    networks:
      - testcenter