version: '3.7'

x-env-mysql: &env-mysql
  MYSQL_DATABASE: iqb_tba_testcenter
  MYSQL_USER: iqb_tba_db_user
  MYSQL_PASSWORD: iqb_tba_db_password

x-env-initdata: &env-initdata
  SUPERUSER_NAME: super
  SUPERUSER_PASSWORD: user123
  WORKSPACE_NAME: example_workspace
  TEST_LOGIN_NAME: test
  TEST_LOGIN_PASSWORD: user123

services:

  testcenter-db:
    image: mysql:5.7
    container_name: testcenter-db
    environment:
      <<: *env-mysql
      MYSQL_ROOT_PASSWORD: secret_root_pw
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "9091:3306"

  testcenter-backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: testcenter-backend
    environment:
      <<: *env-mysql
      <<: *env-initdata
      MYSQL_HOST: testcenter-db
      MYSQL_PORT: 3306
    depends_on:
      - testcenter-db
    volumes:
      - ./testcenter-backend/data:/var/www/html/vo_data
      - vendor_backend:/var/www/html/vendor
    ports:
      - "9092:80"


volumes:
  dbdata:
    driver: local
  vendor_backend:
    driver: local
