services:
  testcenter-backend:
    environment:
      OVERRIDE_CONFIG: |
        [fileService]
        external=testcenter-file-service/
        [broadcastingService]
        external=testcenter-broadcasting-service:3000/

  testcenter-frontend:
    command: "npx ng serve --configuration e2e --disable-host-check --host 0.0.0.0"

  testcenter-e2e:
    container_name: testcenter-e2e
    depends_on:
      testcenter-backend:
        condition: service_healthy
    build:
      context: ..
      dockerfile: docker/e2e.Dockerfile
    environment:
      - CYPRESS_baseUrl=http://testcenter-frontend:4200
    entrypoint: sh -c "cypress run --browser chrome"
    volumes:
      - ../e2e/cypress:/app/cypress
      - ../e2e/cypress.e2e.config.js:/app/cypress.config.js
      - ../sampledata:/sampledata
    networks:
      - testcenter
