version: '3.7'

services:

  testcenter-broadcasting-service-dev:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: testcenter-broadcasting-service-dev
    volumes:
      - ../:/app
      - /app/node_modules
    ports:
      - '3000:3000'

