# Compose file for local development and testing. Images are built from
# local directories which need to be cloned from the repository.
version: '3.9'

services:
  testcenter-backend:
    image: iqbberlin/testcenter-backend:current-prod
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
      target: prod
    volumes:
      - /dev/null:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini # disable xdebug bc not available in prod-image

  testcenter-frontend:
    image: iqbberlin/testcenter-frontend:current-prod
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
      target: prod
    volumes:
      - ../frontend/config/nginx.conf:/etc/nginx/templates/default.conf.template

  testcenter-broadcasting-service:
    image: iqbberlin/testcenter-broadcasting-service:current-prod
    build:
      context: ..
      dockerfile: docker/broadcasting-service.Dockerfile
      target: prod

  testcenter-file-service:
    image: iqbberlin/testcenter-file-service:current-prod
    build:
      context: ..
      dockerfile: docker/file-service.Dockerfile

  testcenter-db:
    image: iqbberlin/testcenter-db:current
    build:
      context: ..
      dockerfile: docker/database.Dockerfile