services:
  testcenter-file-service:
    volumes:
      - ../sampledata:/var/www/html
      - ../sampledata/SAMPLE_UNITCONTENTS.HTM:/var/www/html/ws_1/Resource/SAMPLE_UNITCONTENTS.HTM
    environment:
      CACHE_SERVICE_INCLUDE_FILES: off

  testcenter-task-runner-file-service:
    extends:
      file: docker-compose.dev.yml
      service: testcenter-task-runner
    depends_on:
      testcenter-file-service:
        condition: service_started
      testcenter-cache-service:
        condition: service_started

  testcenter-task-runner-backend:
    extends:
      file: docker-compose.dev.yml
      service: testcenter-task-runner
    depends_on:
      testcenter-backend:
        condition: service_healthy
      testcenter-cache-service:
        condition: service_started
