version: '3.9'

services:
  testcenter-file-service:
    volumes:
      - ../sampledata:/var/www/html
      - ../sampledata/SAMPLE_UNITCONTENTS.HTM:/var/www/html/ws_1/Resource/SAMPLE_UNITCONTENTS.HTM
    environment:
      CACHE_SERVICE_INCLUDE_FILES: off