apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cache-server
spec:
  selector:
    app: {{ .Release.Name }}-cache-server-pod
  ports:
    - port: 6379
      targetPort: http-container
