test-backend-unit:
  stage: test
  rules:
    - !reference [ .backend-change, rules ]
    - if: $CI_PIPELINE_SOURCE == "external_pull_request_event" || $CI_PIPELINE_SOURCE == "web"
    - if: "$CI_COMMIT_TAG"
  dependencies:
    - build-backend
  script:
    - apk add make
    - make init
    - make test-backend-unit-coverage
  artifacts:
    paths:
      - docs/dist/test-coverage-backend-unit/*
    expire_in: 30 minutes

test-frontend-unit:
  stage: test
  rules:
    - !reference [ .frontend-change, rules ]
    - if: $CI_PIPELINE_SOURCE == "external_pull_request_event" || $CI_PIPELINE_SOURCE == "web"
    - if: "$CI_COMMIT_TAG"
  dependencies:
    - build-frontend
  script:
    - apk add make
    - make init
    - make test-frontend-unit-coverage
  artifacts:
    paths:
      - docs/dist/test-coverage-frontend-unit/*
    expire_in: 30 minutes

test-broadcasting-service-unit:
  stage: test
  rules:
    - !reference [ .bs-change, rules ]
    - if: "$CI_COMMIT_TAG"
  dependencies:
    - build-broadcasting-service
  script:
    - apk add make
    - make init
    - make test-broadcasting-service-unit-coverage
  artifacts:
    paths:
      - docs/dist/test-coverage-broadcasting-service-unit/*
    expire_in: 30 minutes

test-backend-api:
  stage: test
  rules:
    - !reference [ .backend-change, rules ]
    - if: $CI_PIPELINE_SOURCE == "external_pull_request_event" || $CI_PIPELINE_SOURCE == "web"
    - if: "$CI_COMMIT_TAG"
  dependencies:
    - build-backend
    - build-db
  script:
    - apk add make
    - make init
    - make test-backend-api

test-file-service-api:
  stage: test
  rules:
    - !reference [ .fs-change, rules ]
    - if: $CI_PIPELINE_SOURCE == "external_pull_request_event" || $CI_PIPELINE_SOURCE == "web"
    - if: "$CI_COMMIT_TAG"
  dependencies:
    - build-file-service
  script:
    - apk add make
    - make init
    - make test-file-service-api

test-backend-initialization:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "external_pull_request_event" || $CI_PIPELINE_SOURCE == "web"
    - if: "$CI_COMMIT_TAG"
  dependencies:
    - build-backend
    - build-db
  script:
    - apk add make
    - make init
    - make test-backend-initialization-general
