apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db-pvc
spec:
  accessModes:
    - {{ .Values.persistence.dbPvcAccessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.dbPvcSize }}
  storageClassName: {{ .Values.persistence.dbPvcStorageClassName }}
