apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-broadcasting-service
spec:
  replicas: {{ .Values.broadcastingService.replicas }}
  {{- if .Values.broadcastingService.strategy }}
  strategy:
  {{- .Values.broadcastingService.strategy | toYaml | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-broadcasting-service-pod
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-broadcasting-service-pod
    spec:
      containers:
        - name: {{ .Chart.Name }}-broadcasting-service-container
          image: iqbberlin/testcenter-broadcasting-service:{{ .Chart.Version }}
          ports:
            - name: http-container
              containerPort: 3000
