apiVersion: v1
kind: Service
metadata:
  name: testcenter-broadcasting-service #hard coded in application as internal address
spec:
  selector:
    app: {{ .Chart.Name }}-broadcasting-service-pod
  ports:
    - name: http-service
      port: 3000
      targetPort: http-container
