apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  annotations:
    {{- include "config.annotations" . | nindent 4 }}
data:
  MYSQL_DATABASE: {{ .Values.config.mysqlDatabase | quote }}
  MYSQL_USER: {{ .Values.config.mysqlUser | quote }}
