apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  annotations:
    {{- include "config.annotations" . | nindent 4 }}
stringData:
  PASSWORD_SALT: {{ .Values.secret.passwordSalt | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.mysqlRootPassword | quote }}
  MYSQL_PASSWORD: {{ .Values.secret.mysqlPassword | quote }}