apiVersion: v1
kind: Service
metadata:
  name: testcenter-broadcasting-service # !!! Hard coded in application as internal address !!! @TODO: Should be '{{ .Release.Name }}-broadcasting-service'
spec:
  selector:
    app: {{ .Release.Name }}-broadcasting-pod
  ports:
    - name: http-service
      port: 3000
      targetPort: http-container
