apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-cache-server-pvc
spec:
  accessModes:
    - {{ .Values.persistence.cacheServerPvcAccessMode }}
  storageClassName: {{ .Values.persistence.cacheServerPvcStorageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.cacheServerPvcSize }}
