apiVersion: v1
kind: Service
metadata:
  name: testcenter-cache-server-service #hard coded in application as internal address
spec:
  selector:
    app: {{ .Release.Name }}-cache-server-pod
  ports:
    - name: http-service
      port: 6379
      targetPort: http-container
