apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-db
spec:
  replicas: {{ .Values.database.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-db-pod
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/app/config/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/app/config/secret.yaml") . | sha256sum }}
      labels:
        app: {{ .Chart.Name }}-db-pod
    spec:
      containers:
        - name: {{ .Chart.Name }}-db-container
          image: mysql:8.0
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_INITDB_SKIP_TZINFO
              value: "true"
          args: [
            "--explicit-defaults-for-timestamp=TRUE",
            "--sql-mode=PIPES_AS_CONCAT,ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION",
            "--tls-version=TLSv1.2,TLSv1.3",
            "--max-connections=500",
            "--log_error_verbosity=1"
          ]
          ports:
            - name: mysql-container
              containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - --user=${MYSQL_USER}
                - -h
                - 127.0.0.1
                - --silent
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - --user=${MYSQL_USER}
                - -h
                - 127.0.0.1
                - --silent
            initialDelaySeconds: 30
            periodSeconds: 300  # 5 minutes
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: dbdata
