apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbdata
spec:
  accessModes:
    - {{ .Values.volume.dbdata.accessMode }}
  resources:
    requests:
      storage: {{ .Values.volume.dbdata.size }}
  storageClassName: {{ .Values.volume.dbdata.storageClassName }}
