apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-cache-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-cache-server-pod
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-cache-server-pod
    spec:
      containers:
        - name: {{ .Chart.Name }}-cache-server-container
          image: "{{ .Values.image.cacheServer.registryPath }}redis:{{ .Values.image.cacheServer.tag }}"
          command:
            - bash
          args:
            - "-c"
            - "redis-server"
            - "--maxmemory"
            - "111Mi"
            - "--maxmemory-policy"
            - "volatile-lru"
          ports:
            - name: http-container
              containerPort: 6379
          # vielleicht nur der Volume mount benötigt
          volumeMounts:
            - name: lv-storage
              mountPath: /data
      volumes:
        - name: lv-storage
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-cache-server-pvc
