apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache-server-pvc
spec:
  accessModes:
    - {{ .Values.volume.cache.accessMode }}
  storageClassName: {{ .Values.volume.cache.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.volume.cache.size }}
