#  Compose file for production environment. Images are NOT locally built but
#  downloaded from Docker-Hub. For certificate setup refer to the README.
version: '3.7'

services:

  traefik:
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.options=default@file"
      - "--providers.file.filename=/ssl-config.yml"
    ports:
      - "${TLS_PORT}:443"
    volumes:
      - ./config/certs/:/certs/
      - ./config/ssl-config.yml:/ssl-config.yml

  testcenter-backend:
    labels:
      - "traefik.http.routers.testcenter-backend.tls=true"

  testcenter-frontend:
    labels:
      - "traefik.http.routers.testcenter-frontend.tls=true"

  testcenter-broadcasting-service:
    labels:
      - "traefik.http.routers.testcenter-broadcasting-service.tls=true"
