#  Compose file for production environment. Images are NOT locally built but
#  downloaded from Docker-Hub. This is the non-TLS variant using unencrypted
#  communication.

services:
  testcenter-db:
    image: ${DOCKERHUB_PROXY}iqbberlin/testcenter-db:${VERSION}
    command:
      - --log_error_verbosity=1

  testcenter-backend:
    image: ${DOCKERHUB_PROXY}iqbberlin/testcenter-backend:${VERSION}
    volumes:
      - testcenter_backend_vo_data:/var/www/data

  testcenter-frontend:
    image: ${DOCKERHUB_PROXY}iqbberlin/testcenter-frontend:${VERSION}
    volumes:
      - ./config/nginx.conf:/etc/nginx/templates/default.conf.template

  testcenter-broadcasting-service:
    image: ${DOCKERHUB_PROXY}iqbberlin/testcenter-broadcasting-service:${VERSION}

  testcenter-file-service:
    image: ${DOCKERHUB_PROXY}iqbberlin/testcenter-file-service:${VERSION}
