#  Compose file for production environment. Images are NOT locally built but
#  downloaded from Docker-Hub. This is the non-TLS variant using unencrypted
#  communication.

services:
  traefik:
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.options=default@file"
      #- "--certificatesresolvers.iqbresolver.acme.tlschallenge=true"
      ## - "--certificatesresolvers.iqbresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      #- "--certificatesresolvers.iqbresolver.acme.email=admin.name@company.com"
      #- "--certificatesresolvers.iqbresolver.acme.storage=/letsencrypt/acme.json"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/tls-config.yml"
    ports:
      - "${TLS_PORT}:443"
    volumes:
      - "./config/certs/:/certs/"
      #- "./config/certs/:/letsencrypt"
      - "./config/tls-config.yml:/tls-config.yml"

  testcenter-db:
    image: ${DOCKERHUB_PROXY}mysql:8.0
    command:
      - "--explicit-defaults-for-timestamp=TRUE"
      - "--sql-mode=PIPES_AS_CONCAT,ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
      - "--tls-version=TLSv1.2,TLSv1.3"
      - "--max-connections=500"
      - "--log_error_verbosity=1"

  testcenter-backend:
    image: ${DOCKERHUB_PROXY}iqbberlin/testcenter-backend:${VERSION}
    labels:
      - "traefik.http.routers.testcenter-backend.tls=true"
      #- "traefik.http.routers.testcenter-backend.tls.certResolver=iqbresolver"
      - "traefik.http.middlewares.tls-security-headers-backend.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.tls-security-headers-backend.headers.stsIncludeSubdomains=true"
      - "traefik.http.routers.testcenter-backend.middlewares=testcenter-backend-stripprefix, security-headers-backend, tls-security-headers-backend"
    volumes:
      - testcenter_backend_vo_data:/var/www/testcenter/data

  testcenter-frontend:
    image: ${DOCKERHUB_PROXY}iqbberlin/testcenter-frontend:${VERSION}
    labels:
      - "traefik.http.routers.testcenter-frontend.tls=true"
      #- "traefik.http.routers.testcenter-frontend.tls.certResolver=iqbresolver"
      #- "traefik.http.routers.testcenter-frontend.tls.domains[0].main=${HOSTNAME}"
      #- "traefik.http.routers.testcenter-frontend.tls.domains[0].sans=www.${HOSTNAME}"
      - "traefik.http.middlewares.tls-security-headers-frontend.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.tls-security-headers-frontend.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.stripwww-fe.redirectregex.regex=^http(s?)://www.${HOSTNAME}/(.*)"
      - "traefik.http.middlewares.stripwww-fe.redirectregex.replacement=http$${1}://${HOSTNAME}/$${2}"
      - "traefik.http.routers.testcenter-frontend.middlewares=security-headers-frontend, tls-security-headers-frontend, stripwww-fe"

  testcenter-broadcasting-service:
    image: ${DOCKERHUB_PROXY}iqbberlin/testcenter-broadcasting-service:${VERSION}
    labels:
      - "traefik.http.routers.testcenter-broadcasting-service.tls=true"
      #- "traefik.http.routers.testcenter-broadcasting-service.tls.certResolver=iqbresolver"
      - "traefik.http.middlewares.tls-security-headers-bs.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.tls-security-headers-bs.headers.stsIncludeSubdomains=true"
      - "traefik.http.routers.testcenter-broadcasting-service.middlewares=testcenter-broadcasting-service-stripprefix, security-headers-bs, tls-security-headers-bs"

  testcenter-file-service:
    image: ${DOCKERHUB_PROXY}iqbberlin/testcenter-file-service:${VERSION}
    labels:
      - "traefik.http.routers.testcenter-file-service.tls=true"
      #- "traefik.http.routers.testcenter-file-service.tls.certResolver=iqbresolver"
      - "traefik.http.middlewares.tls-security-headers-fs.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.tls-security-headers-fs.headers.stsIncludeSubdomains=true"
      - "traefik.http.routers.testcenter-file-service.middlewares=testcenter-file-service-stripprefix, security-headers-fs, tls-security-headers-fs"
