{{- if .Values.persistence.longhornUIEnabled }}

{{- if .Values.ingress.traefikEnabled }}

# Longhorn UI
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: svc-longhorn-headers
  namespace: longhorn-system
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"

{{- end }}

{{- end }}
