config:
  hostname: 192.168.49.2
  port: 80
  tlsPort: 443
  tlsEnabled: off
  mysqlDatabase: iqb_tba_testcenter
  mysqlUser: iqb_tba_db_user
  broadcastServiceEnabled: true
  fileServiceEnabled: true
  cacheServiceRam: 1073741824
  cacheServiceIncludeFiles: false
  dockerDaemonMtu: 1500
  dockerhubProxy: ''
  restartPolicy: always
  overwriteInstallation: no
  skipReadFiles: no
  skipDbIntegrity: no
  noSampleData: no

secret:
  passwordSalt: t
  mysqlRootPassword: o8en6jSGLyVKNZUN
  mysqlPassword: fEaU5COJYXv2atau

backend:
  replicas: 1

broadcastingService:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

cacheService:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

database:
  replicas: 1

frontend:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

fileService:
  replicas: 1

volume:
  vodata:
    storageClassName: standard
    accessMode: ReadWriteOnce
    size: 2Gi
  dbdata:
    storageClassName: standard
    accessMode: ReadWriteOnce
    size: 2Gi
  cache:
    storageClassName: standard
    accessMode: ReadWriteOnce
    size: 5Gi
